### PR TITLE
WithdrawalsController test added

### PR DESCRIPTION
**Pull request by enesacikoglu**

### CODE REVIEW

**Comment by pilloPl** [comment]
Hi, 

Huge thanks!

can you briefly describe why this test is added (in the context of CQRS) and why it's not added to all of the modules?

**Comment by enesacikoglu** [comment]
Hi,

Thanks for reply.

Sorry for lack of explanation.It was a kind of starting commit that covers acting of controller as slice test.

If it is okey for you, I would like to contribute more.

Please feel free to delete,If you think it is not related with the context.

Thanks.
Enes

**Comment by pilloPl** [comment]
It is a valuable test, but not in the context of what we are trying to show here. 

Thanks for this! If you want to collaborate with us, here is thing that we want to do next:

migrate and check if that project works with Java 11 :)

Would you like to do that?

**Comment by enesacikoglu** [comment]
Thanks.

Yes I would like to take it 😊

I will migrate and modify this pull request.

**Comment by pilloPl** [comment]
Great!

I will close this one, please provide another PR :)

THANK YOU!

**Pull request closed without merging**
